#!/usr/bin/perl

# find data/ -type d -print | sort |

while(my $dir = <data/*>) {
    chomp $dir;
    my $alto_list = $dir;
    $alto_list =~ s|data/||;
    if(open($list,">alto_file_lists/$alto_list\.xml")) {
	print $list  '<h:p xmlns:h="http://www.w3.org/1999/xhtml">'."\n";
	while(my $file = <$dir/*xml>) {
	    print $list "<h:a href=\"$file\"/>\n";
	}
	print$list   "</h:p>\n";
    }

}
