#!/bin/bash

#
# sorry, this will most likely not work on your computer
# 

#java -jar  ~/saxon/saxon9he.jar -s:luxdorph-bibliografi.xml -xsl:altototei.xsl

saxon-xslt luxdorph-bibliografi.xml altototei.xsl