#!/usr/bin/perl -w

my $saxon = "java -jar ~/saxon/saxon9he.jar";

while(my $file = <alto_file_lists/*.xml>) {

    my $tei_file = $file;
    $tei_file =~ s/alto_file_lists/tei_dir/;
    print "doing $file\n";
    system("$saxon luxdorph-bibliografi.xml altototei.xsl alto_file=$file | xmllint --format - > $tei_file");

}
