#!/usr/bin/perl -w

while(my $file = <alto_file_lists/*.xml>) {

    my $tei_file = $file;
    $tei_file =~ s/alto_file_lists/tei_dir/;

    system("saxon-xslt luxdorph-bibliografi.xml altototei.xsl alto_files=$file | xmllint --format - > $tei_file");

}
